AWSTemplateFormatVersion: "2010-09-09"
Description: This template creates a AWS EKS Cluster.  
Parameters:
  ClusterName:
    Type: String
    Description: Name of the EKS cluster
    Default: safran-internal-eks-cluster
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: ID of the Amazon VPC for the cluster
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnet IDs in the VPC
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 key pair to associate with the worker nodes
  NodeGroupName:
    Type: String
    Description: Name of the EKS node group
  NodeInstanceType:
    Type: String
    Description: EC2 instance type for the worker nodes
    Default: t3.micro
  DesiredCapacity:
    Type: Number
    Description: Desired number of worker nodes
    Default: 2
    MinValue: 1
    MaxValue: 4

Resources:
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub rol-${ClusterName}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        #- arn:aws:iam::aws:policy/AmazonEKSVPCResourceController

  ClusterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the EKS cluster
      VpcId: !Ref VpcId
      SecurityGroupIngress: 
        - IpProtocol: -1  
          FromPort: -1  
          ToPort: -1  
          CidrIp: 0.0.0.0/0  
      SecurityGroupEgress: 
        - IpProtocol: -1  
          FromPort: -1  
          ToPort: -1  
          CidrIp: 0.0.0.0/0  

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        EndpointPrivateAccess: true
        EndpointPublicAccess: true
        SecurityGroupIds:
          - !Ref ClusterSecurityGroup
        SubnetIds: !Ref SubnetIds

  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub rol-${ClusterName}-node-instance
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  NodeGroup:
    Type: AWS::EKS::Nodegroup
    DependsOn: EKSCluster
    Properties:
      ClusterName: !Ref ClusterName
      NodegroupName: !Ref NodeGroupName
      CapacityType: ON_DEMAND
      InstanceTypes:
        - !Ref NodeInstanceType
      NodeRole: !GetAtt NodeInstanceRole.Arn
      Subnets: !Ref SubnetIds
      ScalingConfig:
        DesiredSize: !Ref DesiredCapacity
        MinSize: 1
        MaxSize: 4
      

Outputs:
  ClusterNameOutput:
    Description: Name of the EKS cluster
    Value: !Ref ClusterName
  NodeGroupNameOutput:
    Description: Name of the EKS node group
    Value: !Ref NodeGroupName
