# Fetch dependencies
FROM golang:1.22 AS lint-test

WORKDIR /workdir
COPY . .

# Install tools
RUN apt update && apt install -y \
    rpm \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.57.2

# Lint
RUN golangci-lint -v run --timeout=3m

# Test
RUN make test

# Export test result
FROM scratch
COPY --from=lint-test /workdir/dist/report.xml /workdir/dist/coverage.xml /
